version: "3.9"

networks:
  modlib-net:
    driver: bridge
services:
  api:    
    container_name: modlib
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - modlib-net
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=123
      -  POSTGRES_DB=modLib
    ports:
      - "5432:5432"
    networks:
      - modlib-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:    